---
- name: Common ansible playbook
  hosts: myserver
  
  vars:
      debian: wheezy
      ntp_server: fr.pool.ntp.org
      nginx_port: 80
      nginx_workers: 4

  roles:
    - common
    - ntp
    - git
    - rmate
    - php-fpm # or hhvm
    # - hhvm # or php-fpm
    - composer
    - nginx
    - mysql
    - python
    - redis