---
- name: Common ansible playbook
  hosts: myserver
  
  vars:
      debian: wheezy
      ntp_server: fr.pool.ntp.org
      nginx_port: 80
      nginx_workers: 4
      php_engine: fpm # (hhvm or fpm)

  roles:
    - common
    - ntp
    - git
    - rmate
    - { role: php-fpm, when: php_engine == 'fpm' }
    - { role: php-hhvm, when: php_engine == 'hhvm' }
    - php-extensions
    - composer
    - nginx
    - mysql
    - python
    - redis